namespace TruLoad.Backend.Common.Constants;

/// <summary>
/// Centralized branding constants for TruLoad system.
/// Used across PDF documents, UI components, and system branding.
/// </summary>
public static class BrandingConstants
{
    /// <summary>
    /// Official color palette for Kenya road authorities (KURA/KeNHA/KeRRA).
    /// </summary>
    public static class Colors
    {
        /// <summary>
        /// Kenya road authorities primary black color.
        /// Used for text and primary branding elements.
        /// </summary>
        public const string KuraBlack = "#313232ff";

        /// <summary>
        /// Kenya road authorities primary blue color.
        /// Used for headers, titles, and official documents.
        /// </summary>
        public const string KuraBlue = "#0066CC";

        /// <summary>
        /// Official government red for warnings and prohibitions.
        /// Used for prohibition orders, critical alerts, and urgent notices.
        /// </summary>
        public const string OfficialRed = "#CC0000";

        /// <summary>
        /// Official government green for compliance and clearance.
        /// Used for compliance certificates, clearances, and approvals.
        /// </summary>
        public const string OfficialGreen = "#006633";

        /// <summary>
        /// Orange for special releases and conditional approvals.
        /// Used for special release certificates and conditional clearances.
        /// </summary>
        public const string OfficialOrange = "#FF8C00";

        /// <summary>
        /// Gray for neutral elements and secondary text.
        /// </summary>
        public const string NeutralGray = "#6B7280";
    }

    /// <summary>
    /// Organization names and legal identifiers.
    /// </summary>
    public static class Organization
    {
        public const string RepublicOfKenya = "REPUBLIC OF KENYA";
        public const string KenyaRoadsAuthority = "Kenya Urban Roads Authority (KURA)";
        public const string RoadsEnforcementDivision = "ROADS ENFORCEMENT DIVISION";
        public const string TruLoadSystemName = "TRULOAD WEIGHING SYSTEM";
    }

    /// <summary>
    /// Legal framework identifiers.
    /// </summary>
    public static class LegalFramework
    {
        public const string EAC = "EAC";
        public const string TrafficAct = "TRAFFIC_ACT";
        public const string Both = "BOTH";

        public static readonly string[] ValidFrameworks = { EAC, TrafficAct, Both };
    }

    /// <summary>
    /// Axle grouping identifiers (EAC standard).
    /// </summary>
    public static class AxleGrouping
    {
        public const string GroupA = "A";
        public const string GroupB = "B";
        public const string GroupC = "C";
        public const string GroupD = "D";

        public static readonly string[] ValidGroupings = { GroupA, GroupB, GroupC, GroupD };
    }

    /// <summary>
    /// Document footer text constants.
    /// </summary>
    public static class DocumentFooter
    {
        public const string OfficialSealText = "Official System Generated Document - Digitally Signed";
        public const string DisclaimerText = "This is a computer-generated document. No signature is required for validity.";
        public const string GeneratedByText = "Generated by TruLoad Weighing System";
    }

    /// <summary>
    /// Official logo file names relative to wwwroot/images/.
    /// Used in PDF document headers for official branding.
    /// </summary>
    public static class Logos
    {
        public const string KuraLogo = "kura-logo.png";
        public const string KenhaLogo = "kenha-logo.png";
        public const string KenyaPoliceLogo = "kenya-police-logo.png";
        public const string CourtOfArmsKenya = "court-of-arms-kenya.png";
        public const string JudicialLogo = "judiciallogo.png";
        public const string EacActLogo = "eac-act-logo.png";
        public const string EcitizenLogo = "ecitizen-logo.png";
        public const string KuraWeighLogo = "kuraweigh-logo.png";
        public const string NtsaLogo = "ntsa-logo.png";

        /// <summary>
        /// Default TruLoad platform logo, used as fallback when org has no custom logo.
        /// </summary>
        public const string TruLoadLogo = "truload-logo.png";
    }

    /// <summary>
    /// Status indicator image file names relative to wwwroot/images/.
    /// Used in PDF documents to show compliance status visually.
    /// </summary>
    public static class StatusImages
    {
        public const string GreenButton = "greenbutton.png";
        public const string RedButton = "redbutton.jpg";
        public const string TaggedIcon = "tagged.png";
    }

    /// <summary>
    /// File storage folder names.
    /// </summary>
    public static class StorageFolders
    {
        public const string WeightTickets = "weight-tickets";
        public const string ProhibitionOrders = "prohibition-orders";
        public const string ComplianceCertificates = "compliance-certificates";
        public const string SpecialReleaseCertificates = "special-release-certificates";
        public const string LoadCorrectionMemos = "load-correction-memos";
        public const string CaseFiles = "case-files";
        public const string Evidence = "evidence";
        public const string Reports = "reports";
    }
}
