// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using truload_backend.Data;

#nullable disable

namespace truload_backend.Migrations
{
    [DbContext(typeof(TruLoadDbContext))]
    partial class TruLoadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_logs_created_at");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("idx_audit_logs_resource_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("idx_audit_logs_resource_type");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AxleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("axle_code");

                    b.Property<string>("AxleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("axle_name");

                    b.Property<int>("AxleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("axle_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GvwPermissibleKg")
                        .HasColumnType("integer")
                        .HasColumnName("gvw_permissible_kg");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_standard");

                    b.Property<string>("LegalFramework")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("BOTH")
                        .HasColumnName("legal_framework");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisualDiagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("visual_diagram_url");

                    b.HasKey("Id");

                    b.HasIndex("AxleCode")
                        .IsUnique()
                        .HasDatabaseName("idx_axle_configurations_code_unique");

                    b.HasIndex("AxleNumber")
                        .HasDatabaseName("idx_axle_configurations_axle_number");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsStandard")
                        .HasDatabaseName("idx_axle_configurations_standard")
                        .HasFilter("is_standard = true");

                    b.HasIndex("LegalFramework")
                        .HasDatabaseName("idx_axle_configurations_framework");

                    b.HasIndex("IsActive", "DeletedAt")
                        .HasDatabaseName("idx_axle_configurations_active")
                        .HasFilter("is_active = true AND deleted_at IS NULL");

                    b.ToTable("axle_configurations", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleFeeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DemeritPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("demerit_points");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("FeePerKgUsd")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fee_per_kg_usd");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_type");

                    b.Property<decimal>("FlatFeeUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("flat_fee_usd");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LegalFramework")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("legal_framework");

                    b.Property<int?>("OverloadMaxKg")
                        .HasColumnType("integer")
                        .HasColumnName("overload_max_kg");

                    b.Property<int>("OverloadMinKg")
                        .HasColumnType("integer")
                        .HasColumnName("overload_min_kg");

                    b.Property<string>("PenaltyDescription")
                        .HasColumnType("text")
                        .HasColumnName("penalty_description");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("idx_axle_fee_schedule_effective");

                    b.HasIndex("LegalFramework", "FeeType")
                        .HasDatabaseName("idx_axle_fee_schedule_framework_type");

                    b.ToTable("axle_fee_schedules", null, t =>
                        {
                            t.HasCheckConstraint("chk_fee_type", "fee_type IN ('GVW', 'AXLE')");

                            t.HasCheckConstraint("chk_legal_framework", "legal_framework IN ('EAC', 'TRAFFIC_ACT')");
                        });
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AxleCountInGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("axle_count_in_group");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxSpacingFeet")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("max_spacing_feet");

                    b.Property<decimal?>("MinSpacingFeet")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("min_spacing_feet");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TypicalWeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("typical_weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_axle_groups_code_unique");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_axle_groups_active")
                        .HasFilter("is_active = true");

                    b.ToTable("axle_groups", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleWeightReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AxleConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("axle_configuration_id");

                    b.Property<Guid>("AxleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("axle_group_id");

                    b.Property<string>("AxleGrouping")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("axle_grouping");

                    b.Property<int>("AxleLegalWeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("axle_legal_weight_kg");

                    b.Property<int>("AxlePosition")
                        .HasColumnType("integer")
                        .HasColumnName("axle_position");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("TyreTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tyre_type_id");

                    b.HasKey("Id");

                    b.HasIndex("AxleConfigurationId")
                        .HasDatabaseName("idx_axle_weight_ref_config_id");

                    b.HasIndex("AxleGroupId")
                        .HasDatabaseName("idx_axle_weight_ref_group_id");

                    b.HasIndex("TyreTypeId")
                        .HasDatabaseName("idx_axle_weight_ref_tyre_type_id");

                    b.HasIndex("AxleConfigurationId", "AxlePosition")
                        .IsUnique()
                        .HasDatabaseName("idx_axle_weight_ref_config_position_unique");

                    b.ToTable("axle_weight_references", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDemeritPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_demerit_points");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DrivingLicenseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("driving_license_no");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_names");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsProfessionalDriver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_professional_driver");

                    b.Property<string>("LicenseClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_class");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expiry_date");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_issue_date");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("license_status");

                    b.Property<string>("Nationality")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Kenya")
                        .HasColumnName("nationality");

                    b.Property<string>("NtsaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ntsa_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.Property<DateTime?>("SuspensionEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspension_end_date");

                    b.Property<DateTime?>("SuspensionStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspension_start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DrivingLicenseNo")
                        .IsUnique()
                        .HasDatabaseName("idx_drivers_license_no_unique");

                    b.HasIndex("IdNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_drivers_id_number_unique");

                    b.HasIndex("NtsaId")
                        .IsUnique()
                        .HasDatabaseName("idx_drivers_ntsa_id_unique");

                    b.HasIndex("LicenseStatus", "IsActive")
                        .HasDatabaseName("idx_drivers_license_status_active");

                    b.HasIndex("SuspensionStartDate", "SuspensionEndDate")
                        .HasDatabaseName("idx_drivers_suspension_dates")
                        .HasFilter("suspension_start_date IS NOT NULL");

                    b.ToTable("drivers", null, t =>
                        {
                            t.HasCheckConstraint("chk_driver_license_status", "license_status IN ('active', 'suspended', 'revoked', 'expired')");
                        });
                });

            modelBuilder.Entity("TruLoad.Backend.Models.DriverDemeritRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseRegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_register_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("FeeScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_schedule_id");

                    b.Property<bool>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_expired");

                    b.Property<string>("LegalFramework")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("legal_framework");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OverloadKg")
                        .HasColumnType("integer")
                        .HasColumnName("overload_kg");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("PenaltyAmountUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("penalty_amount_usd");

                    b.Property<int>("PointsAssigned")
                        .HasColumnType("integer")
                        .HasColumnName("points_assigned");

                    b.Property<DateTime>("PointsExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("points_expiry_date");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("violation_date");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("violation_type");

                    b.Property<Guid?>("WeighingId")
                        .HasColumnType("uuid")
                        .HasColumnName("weighing_id");

                    b.HasKey("Id");

                    b.HasIndex("FeeScheduleId");

                    b.HasIndex("PointsExpiryDate")
                        .HasDatabaseName("idx_demerit_records_expiry_date")
                        .HasFilter("is_expired = false");

                    b.HasIndex("DriverId", "ViolationDate")
                        .HasDatabaseName("idx_demerit_records_driver_date");

                    b.HasIndex("PaymentStatus", "DriverId")
                        .HasDatabaseName("idx_demerit_records_payment_driver");

                    b.ToTable("driver_demerit_records", null, t =>
                        {
                            t.HasCheckConstraint("chk_demerit_legal_framework", "legal_framework IN ('EAC', 'TRAFFIC_ACT')");

                            t.HasCheckConstraint("chk_demerit_payment_status", "payment_status IN ('pending', 'paid', 'waived')");

                            t.HasCheckConstraint("chk_demerit_points_range", "points_assigned >= 0 AND points_assigned <= 20");

                            t.HasCheckConstraint("chk_demerit_violation_type", "violation_type IN ('GVW_OVERLOAD', 'AXLE_OVERLOAD', 'PERMIT_VIOLATION', 'OTHER')");
                        });
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("idx_roles_code");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("idx_users_department_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("idx_users_organization_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("idx_users_station_id");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("org_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_organizations_code");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_permissions_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_permissions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_permissions_active");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.PermitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AxleExtensionKg")
                        .HasColumnType("integer")
                        .HasColumnName("axle_extension_kg");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GvwExtensionKg")
                        .HasColumnType("integer")
                        .HasColumnName("gvw_extension_kg");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("validity_days");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_permit_types_code");

                    b.ToTable("permit_types", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("idx_role_permissions_permission");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.RotationShift", b =>
                {
                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("rotation_id");

                    b.Property<Guid>("WorkShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_shift_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.HasKey("RotationId", "WorkShiftId");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("rotation_shifts", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.ShiftRotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BreakDuration")
                        .HasColumnType("integer")
                        .HasColumnName("break_duration");

                    b.Property<string>("BreakUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("break_unit");

                    b.Property<Guid?>("CurrentActiveShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_active_shift_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("NextChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_change_date");

                    b.Property<int>("RunDuration")
                        .HasColumnType("integer")
                        .HasColumnName("run_duration");

                    b.Property<string>("RunUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("run_unit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CurrentActiveShiftId");

                    b.ToTable("shift_rotations", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("StationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("station_name");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_type");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<bool>("SupportsBidirectional")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_bidirectional");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("idx_stations_code_alias");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StationCode")
                        .IsUnique()
                        .HasDatabaseName("idx_stations_code");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.ToleranceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("applies_to");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("legal_framework");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ToleranceKg")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_kg");

                    b.Property<decimal>("TolerancePercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tolerance_percentage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_tolerance_settings_code");

                    b.HasIndex("EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("idx_tolerance_settings_effective_dates");

                    b.ToTable("tolerance_settings", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.TyreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("TypicalMaxWeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("typical_max_weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_tyre_types_code_unique");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_tyre_types_active")
                        .HasFilter("is_active = true");

                    b.ToTable("tyre_types", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.UserShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<Guid?>("ShiftRotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_rotation_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_shift_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftRotationId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("user_shifts", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WeighingAxle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AxleConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("axle_configuration_id");

                    b.Property<Guid>("AxleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("axle_group_id");

                    b.Property<string>("AxleGrouping")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("axle_grouping");

                    b.Property<int>("AxleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("axle_number");

                    b.Property<Guid?>("AxleWeightReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("axle_weight_reference_id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("FeeUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fee_usd");

                    b.Property<int>("MeasuredWeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("measured_weight_kg");

                    b.Property<int>("PermissibleWeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("permissible_weight_kg");

                    b.Property<Guid?>("TyreTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tyre_type_id");

                    b.Property<Guid>("WeighingId")
                        .HasColumnType("uuid")
                        .HasColumnName("weighing_id");

                    b.HasKey("Id");

                    b.HasIndex("AxleConfigurationId")
                        .HasDatabaseName("idx_weighing_axles_configuration");

                    b.HasIndex("AxleGroupId")
                        .HasDatabaseName("idx_weighing_axles_group");

                    b.HasIndex("AxleWeightReferenceId");

                    b.HasIndex("TyreTypeId");

                    b.HasIndex("WeighingId")
                        .HasDatabaseName("idx_weighing_axles_weighing");

                    b.HasIndex("WeighingId", "AxleNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_weighing_axles_weighing_axle_unique");

                    b.ToTable("weighing_axles", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("grace_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShiftCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shift_code");

                    b.Property<string>("ShiftName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shift_name");

                    b.Property<decimal>("TotalHoursPerWeek")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_hours_per_week");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("work_shifts", (string)null);
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WorkShiftSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BreakHours")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("break_hours");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("EndTimeStr")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("end_time_str");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working_day");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("StartTimeStr")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("start_time_str");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_shift_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("work_shift_schedules", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AuditLog", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleConfiguration", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleWeightReference", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.AxleConfiguration", "AxleConfiguration")
                        .WithMany("AxleWeightReferences")
                        .HasForeignKey("AxleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.AxleGroup", "AxleGroup")
                        .WithMany("AxleWeightReferences")
                        .HasForeignKey("AxleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.TyreType", "TyreType")
                        .WithMany("AxleWeightReferences")
                        .HasForeignKey("TyreTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AxleConfiguration");

                    b.Navigation("AxleGroup");

                    b.Navigation("TyreType");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Department", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.DriverDemeritRecord", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Driver", "Driver")
                        .WithMany("DemeritRecords")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.AxleFeeSchedule", "FeeSchedule")
                        .WithMany()
                        .HasForeignKey("FeeScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("FeeSchedule");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Identity.ApplicationUser", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruLoad.Backend.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruLoad.Backend.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.RolePermission", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.RotationShift", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.ShiftRotation", "ShiftRotation")
                        .WithMany("RotationShifts")
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.WorkShift", "WorkShift")
                        .WithMany("RotationShifts")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftRotation");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.ShiftRotation", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.WorkShift", "CurrentActiveShift")
                        .WithMany()
                        .HasForeignKey("CurrentActiveShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentActiveShift");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Station", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.UserShift", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.ShiftRotation", "ShiftRotation")
                        .WithMany("UserShifts")
                        .HasForeignKey("ShiftRotationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruLoad.Backend.Models.Identity.ApplicationUser", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.WorkShift", "WorkShift")
                        .WithMany("UserShifts")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ShiftRotation");

                    b.Navigation("User");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WeighingAxle", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.AxleConfiguration", "AxleConfiguration")
                        .WithMany("WeighingAxles")
                        .HasForeignKey("AxleConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.AxleGroup", "AxleGroup")
                        .WithMany("WeighingAxles")
                        .HasForeignKey("AxleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruLoad.Backend.Models.AxleWeightReference", "AxleWeightReference")
                        .WithMany()
                        .HasForeignKey("AxleWeightReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TruLoad.Backend.Models.TyreType", "TyreType")
                        .WithMany("WeighingAxles")
                        .HasForeignKey("TyreTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AxleConfiguration");

                    b.Navigation("AxleGroup");

                    b.Navigation("AxleWeightReference");

                    b.Navigation("TyreType");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WorkShiftSchedule", b =>
                {
                    b.HasOne("TruLoad.Backend.Models.WorkShift", "WorkShift")
                        .WithMany("WorkShiftSchedules")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleConfiguration", b =>
                {
                    b.Navigation("AxleWeightReferences");

                    b.Navigation("WeighingAxles");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.AxleGroup", b =>
                {
                    b.Navigation("AxleWeightReferences");

                    b.Navigation("WeighingAxles");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Driver", b =>
                {
                    b.Navigation("DemeritRecords");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Organization", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.ShiftRotation", b =>
                {
                    b.Navigation("RotationShifts");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.TyreType", b =>
                {
                    b.Navigation("AxleWeightReferences");

                    b.Navigation("WeighingAxles");
                });

            modelBuilder.Entity("TruLoad.Backend.Models.WorkShift", b =>
                {
                    b.Navigation("RotationShifts");

                    b.Navigation("UserShifts");

                    b.Navigation("WorkShiftSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
