using Microsoft.EntityFrameworkCore;
using TruLoad.Backend.Models.System;

namespace TruLoad.Backend.Data.Seeders.SystemConfiguration;

/// <summary>
/// Seeds initial document sequences for all organizations and all document types generated by the backend.
/// Uses DocumentSeedDefinitions so sequences stay aligned with document conventions (same types, matching ResetFrequency).
/// DocumentNumberService links convention and sequence by OrganizationId + DocumentType when generating numbers.
/// Org-level sequences (StationId = null) are seeded here; station-scoped sequences are created on first use.
/// Idempotent - safe to run multiple times.
/// </summary>
public class DocumentSequenceSeeder
{
    private readonly TruLoadDbContext _context;

    public DocumentSequenceSeeder(TruLoadDbContext context)
    {
        _context = context;
    }

    public async Task SeedAsync()
    {
        var orgs = await _context.Organizations.ToListAsync();
        if (orgs.Count == 0) return;

        foreach (var org in orgs)
        {
            foreach (var entry in DocumentSeedDefinitions.All)
            {
                var exists = await _context.DocumentSequences.AnyAsync(s =>
                    s.OrganizationId == org.Id &&
                    s.StationId == null &&
                    s.DocumentType == entry.DocumentType);

                if (!exists)
                {
                    _context.DocumentSequences.Add(new DocumentSequence
                    {
                        Id = Guid.NewGuid(),
                        OrganizationId = org.Id,
                        StationId = null,
                        DocumentType = entry.DocumentType,
                        CurrentSequence = 0,
                        ResetFrequency = entry.ResetFrequency,
                        LastResetDate = DateTime.UtcNow,
                    });
                }
            }
        }

        await _context.SaveChangesAsync();
    }
}
