name: Build and Deploy TruLoad Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install DevOps Tools
      uses: Bengo-Hub/devops-k8s/.github/actions/install-devops-tools@main

    - name: Debug available secrets
      run: |
        echo "Checking which tokens are available..."
        [[ -n "${{ secrets.GH_PAT }}" ]] && echo "✅ GH_PAT is set" || echo "❌ GH_PAT not found"
        [[ -n "${{ secrets.GIT_SECRET }}" ]] && echo "✅ GITHUB_SECRET is set" || echo "❌ GITHUB_SECRET not found"
        [[ -n "${{ secrets.GIT_TOKEN }}" ]] && echo "✅ GIT_TOKEN is set (default)" || echo "❌ GIT_TOKEN not found"

    - name: Set deployment variables
      run: |
        echo "DEPLOY=true" >> $GITHUB_ENV
        echo "SETUP_DATABASES=true" >> $GITHUB_ENV
        echo "DB_TYPES=postgres,redis,rabbitmq" >> $GITHUB_ENV
        echo "NAMESPACE=truload" >> $GITHUB_ENV
        echo "ENV_SECRET_NAME=truload-backend-env" >> $GITHUB_ENV
        echo "REGISTRY_SERVER=docker.io" >> $GITHUB_ENV
        echo "REGISTRY_NAMESPACE=codevertex" >> $GITHUB_ENV
        echo "VALUES_FILE_PATH=apps/truload-backend/values.yaml" >> $GITHUB_ENV
        echo "APP_NAME=truload-backend" >> $GITHUB_ENV

    - name: Run production deployment
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GIT_SECRET: ${{ secrets.GIT_SECRET }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        GITHUB_SHA: ${{ github.sha }}
        DEPLOY: true
        SETUP_DATABASES: true
        DB_TYPES: postgres,redis,rabbitmq
        NAMESPACE: truload
        ENV_SECRET_NAME: truload-backend-env
        REGISTRY_SERVER: docker.io
        REGISTRY_NAMESPACE: codevertex
        VALUES_FILE_PATH: apps/truload-backend/values.yaml
        APP_NAME: truload-backend
        GIT_USER: ${{ secrets.GIT_USER || 'TruLoad Bot' }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL || 'dev@truload.io' }}
        # Shared database passwords from ERP namespace
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        # TruLoad-specific
        RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
        RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME || 'user' }}
        # .NET secrets
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ASPNET_SECRET: ${{ secrets.ASPNET_SECRET }}
      run: |
        chmod +x build.sh
        # Export shared database passwords (used by setup_env_secrets.sh)
        export POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
        export REDIS_PASSWORD="${REDIS_PASSWORD}"
        export RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD}"
        ./build.sh

    - name: Tag and push :latest
      if: success()
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        set -e
        : "${REGISTRY_SERVER:=docker.io}"
        : "${REGISTRY_NAMESPACE:=codevertex}"
        IMAGE_REPO="${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/truload-backend"
        SHORT_SHA=${GITHUB_SHA::8}
        echo "Tagging ${IMAGE_REPO}:${SHORT_SHA} as :latest"
        echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_SERVER" -u "$REGISTRY_USERNAME" --password-stdin
        docker pull "${IMAGE_REPO}:${SHORT_SHA}" || true
        docker tag "${IMAGE_REPO}:${SHORT_SHA}" "${IMAGE_REPO}:latest"
        docker push "${IMAGE_REPO}:latest"

    - name: Verify API health
      if: success()
      env:
        KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        NS: truload
      run: |
        if [ -z "${KUBE_CONFIG_B64}" ]; then
          echo "⏭️ Skipping health check - no KUBE_CONFIG available"
          exit 0
        fi

        echo "::group::Health check"
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG_B64" | base64 -d > ~/.kube/config

        # Ensure deployment is rolled out
        kubectl rollout status deployment/truload-backend-app -n ${NS} --timeout=300s

        # Try ingress health endpoint
        HOSTS=$(kubectl get ingress -n ${NS} -o jsonpath='{.items[*].spec.rules[*].host}' | tr ' ' '\n' | grep -E '^truloadapitest' || true)
        if [ -n "$HOSTS" ]; then
          STATUS=1
          for H in $HOSTS; do
            echo "Checking https://$H/health ..."
            if curl -sk --max-time 10 "https://$H/health" | grep -Ei "healthy" >/dev/null; then
              echo "✅ Health OK for $H"
              STATUS=0
              break
            fi
          done
          if [ $STATUS -ne 0 ]; then
            echo "⚠️ Health endpoint did not return OK; rollout completed but endpoint may still be initializing"
          fi
        else
          echo "No ingress host found; skipping external health probe"
        fi
        echo "::endgroup::"
